### ISSUE TITLE
Install from pip fails with "ModuleNotFoundError: No module named 'future'"

### ISSUE THREAD

**Issue by johnmbarrett** [mattjj/pyhsmm#104]
This happening on Windows x64 using Anaconda 3. See below command prompt output:

```
(base) C:\Users\LSPS2>conda create -n test pip
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\LSPS2\Anaconda3\envs\test

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.4.5.1         |           py38_0         156 KB
    python-3.8.2               |       h5fd99cc_0        16.0 MB
    setuptools-46.1.3          |           py38_0         538 KB
    wheel-0.34.2               |           py38_0          66 KB
    ------------------------------------------------------------
                                           Total:        16.7 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/win-64::certifi-2020.4.5.1-py38_0
  openssl            pkgs/main/win-64::openssl-1.1.1f-he774522_0
  pip                pkgs/main/win-64::pip-20.0.2-py38_1
  python             pkgs/main/win-64::python-3.8.2-h5fd99cc_0
  setuptools         pkgs/main/win-64::setuptools-46.1.3-py38_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py38_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py38_0

...

(base) C:\Users\LSPS2>activate test

(test) C:\Users\LSPS2>pip install pyhsmm
Collecting pyhsmm
  Using cached pyhsmm-0.1.7.tar.gz (513 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\LSPS2\Anaconda3\envs\test\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LSPS2\\AppData\\Local\\Temp\\pip-install-p_xand58\\pyhsmm\\setup.py'"'"'; __file__='"'"'C:\\Users\\LSPS2\\AppData\\Local\\Temp\\pip-install-p_xand58\\pyhsmm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\LSPS2\AppData\Local\Temp\pip-install-p_xand58\pyhsmm\pip-egg-info'
         cwd: C:\Users\LSPS2\AppData\Local\Temp\pip-install-p_xand58\pyhsmm\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LSPS2\AppData\Local\Temp\pip-install-p_xand58\pyhsmm\setup.py", line 14, in <module>
        from future.standard_library import install_aliases
    ModuleNotFoundError: No module named 'future'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Possibly future is missing from the dependency list? Running `conda install future` then rerunning `pip install pyhsmm` fixes the issue.

**Comment by jxwang59** [comment]
@johnmbarrett  Hello,

I got the same error as below when I attempted to install pyhsmm in anaconda Win 64. But it didn't work when I ran `conda install future` and `pip install pyhsmm`. Do you have any suggestions?  Thanks,

(hmm) C:\Users\jwang223>pip install pyhsmm
Collecting pyhsmm
  Using cached pyhsmm-0.1.7.tar.gz (513 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jwang223\Anaconda3\envs\hmm\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jwang223\\AppData\\Local\\Temp\\pip-install-i6_kbmm5\\pyhsmm\\setup.py'"'"'; __file__='"'"'C:\\Users\\jwang223\\AppData\\Local\\Temp\\pip-install-i6_kbmm5\\pyhsmm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jwang223\AppData\Local\Temp\pip-pip-egg-info-7j7825b2'
         cwd: C:\Users\jwang223\AppData\Local\Temp\pip-install-i6_kbmm5\pyhsmm\
    Complete output (30 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jwang223\AppData\Local\Temp\pip-install-i6_kbmm5\pyhsmm\setup.py", line 76, in <module>
        urlretrieve(eigenurl, eigentarpath)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 247, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 531, in open
        response = meth(req, response)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 640, in http_response
        response = self.parent.error(
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 563, in error
        result = self._call_chain(*args)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 502, in _call_chain
        result = func(*args)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 755, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 531, in open
        response = meth(req, response)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 640, in http_response
        response = self.parent.error(
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 569, in error
        return self._call_chain(*args)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 502, in _call_chain
        result = func(*args)
      File "C:\Users\jwang223\Anaconda3\envs\hmm\lib\urllib\request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    Downloading Eigen...
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rnjv** [comment]
pip install future worked for me but I had to clone and install it with cython.
