### ISSUE TITLE
HTTP 404 error when installing in WSL Debian

### ISSUE THREAD

**Issue by FancyBrush** [mattjj/pyhsmm#112]
OS: Windows Subsystem for Linux, Debian
Miniconda3
command: pip install pyhsmm
Here is the error message:
Collecting pyhsmm
  Using cached pyhsmm-0.1.7.tar.gz (513 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/whr/miniconda3/envs/somoseq/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gnz7uh9d/pyhsmm_0402c4436f404942b8be4c3b7705f5bc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gnz7uh9d/pyhsmm_0402c4436f404942b8be4c3b7705f5bc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vxgwk3u3
         cwd: /tmp/pip-install-gnz7uh9d/pyhsmm_0402c4436f404942b8be4c3b7705f5bc/
    Complete output (30 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gnz7uh9d/pyhsmm_0402c4436f404942b8be4c3b7705f5bc/setup.py", line 76, in <module>
        urlretrieve(eigenurl, eigentarpath)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 248, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 564, in error
        result = self._call_chain(*args)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 756, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/home/whr/miniconda3/envs/somoseq/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    Downloading Eigen...
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

It turns out that the link used to downloading "Eigen" package is not valid anymore.

**Comment by sunqy31** [comment]
I have similar problem installing pyhsmm-autoregressive
OS: ubuntu 22.04
Python: 3.8

Downloading Eigen...
Traceback (most recent call last):
  File "/home/linux1/Downloads/pyhsmm-autoregressive-master/setup.py", line 22, in <module>
    urlretrieve(eigenurl, eigentarpath)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/linux1/anaconda3/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by mikewojnowicz** [comment]
I had similar problems with `pip install pyhsmm`. However, I was able to install the package using `pip install git+https://github.com/mattjj/pyhsmm`. Not sure what the difference is.
