### ISSUE TITLE
Cannot install `pyhsmm` with pip in python 3.8.5

### ISSUE THREAD

**Issue by mikewojnowicz** [mattjj/pyhsmm#118]
```
(env) mwojno01@MW-DS-C02TN1L0GTDY:~/Repos/ssm_star$ pip install pyhsmm
Collecting pyhsmm
  Using cached pyhsmm-0.1.7.tar.gz (513 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/mwojno01/Repos/ssm_star/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dj/ws627fn52hg088j8tqns34n5p7l4r8/T/pip-install-za0ppcz8/pyhsmm/setup.py'"'"'; __file__='"'"'/private/var/folders/dj/ws627fn52hg088j8tqns34n5p7l4r8/T/pip-install-za0ppcz8/pyhsmm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dj/ws627fn52hg088j8tqns34n5p7l4r8/T/pip-pip-egg-info-b5vvj_1t
         cwd: /private/var/folders/dj/ws627fn52hg088j8tqns34n5p7l4r8/T/pip-install-za0ppcz8/pyhsmm/
    Complete output (30 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dj/ws627fn52hg088j8tqns34n5p7l4r8/T/pip-install-za0ppcz8/pyhsmm/setup.py", line 76, in <module>
        urlretrieve(eigenurl, eigentarpath)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 247, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 563, in error
        result = self._call_chain(*args)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 755, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/Users/mwojno01/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    Downloading Eigen...
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mikewojnowicz** [comment]
Update, this problem seems to have been fixed on the master branch (by https://github.com/mattjj/pyhsmm/commit/9e078fc5cdf8ecb81cd358ac2331aca2a89c9064). But the pypi package has not been updated since May 2017 (https://pypi.org/project/pyhsmm/#history).

Any chance of updating the pypi package?
