### ISSUE TITLE
cython 0.22 incompatibility with util/cyutil.py wrapper

### ISSUE THREAD

**Issue by mattjj** [mattjj/pyhsmm#31]
Someone brought this problem to my attention in an email:

```
root@bd63:/home/exp/pyhsmm# python setup.py build_ext --inplace

Traceback (most recent call last):

  File "setup.py", line 35, in <module>

    ext_modules = cythonize('**/*.pyx')

  File "/home/exp/lbshmm/pyhsmm/util/cyutil.py", line 107, in cythonize

    out = true_cythonize(*args,**kwargs)

  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 754, in cythonize

    aliases=aliases)

ValueError: too many values to unpack
```

My unfortunate wrapper in util/cyutil.py depends on some cython internals that changed slightly in 0.22!

**Comment by mattjj** [comment]
A better long-term fix would be to follow standard python packaging conventions (#28).
