### ISSUE TITLE
ImportError: cannot import name get_exe

### ISSUE THREAD

**Issue by gxhrid** [mattjj/pyhsmm#42]
I have add the pyhsmm and pybasicbayes package to pythonpath in the linux evn variables, like,

>export PYTHONPATH=$PYTHONPATH:/home/exp/lbshmm/pyhsmm:/home/exp/lbshmm/pybasicbayes

as an alternative solution to yours in README file.(You might also want to add pyhsmm to your global Python path (e.g. by copying it to your site-packages directory).)

But when I run the sample **animation.py** in your samples dictatory, following error occurs.

root@bd63:/home/exp/lbshmm/pyhsmm# python pyhsmm/examples/animation.py
Warning: the freeimage wrapper of imageio could not be loaded:
Could not find a freeimage library in any of:
/usr/local/lib/python2.7/dist-packages/imageio/
/usr/local/lib/python2.7/dist-packages/imageio/lib
/lib
/usr/lib
/usr/local/lib
Install FreeImage (libfreeimage3) via your package manager or build from source.
Traceback (most recent call last):
  File "pyhsmm/examples/animation.py", line 43, in <module>
    from moviepy.editor import VideoClip
  File "/usr/local/lib/python2.7/dist-packages/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 15, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python2.7/dist-packages/moviepy/config.py", line 37, in <module>
    from imageio.plugins.ffmpeg import get_exe
ImportError: cannot import name get_exe

**is my moviepy or imageio package version unsuitable?**

**Comment by mattjj** [comment]
This doesn't sound like an issue with pyhsmm; it sounds like an issue with getting moviepy working.
