### ISSUE TITLE
Problems installing on Python 3.4

### ISSUE THREAD

**Issue by stevenwong** [mattjj/pyhsmm#71]
Hi all,

I'm using Anaconda's version of Python 3.4 and I get the following error:

    (py34) C:\Users\swong32\Documents>pip install pyhsmm --trusted-host pypi.python.org
    Collecting pyhsmm
      Downloading pyhsmm-0.1.6.tar.gz (491kB)
        100% |################################| 491kB 10.2MB/s
        Complete output from command python setup.py egg_info:
        C:\Program Files\Anaconda3\envs\py34\lib\site-packages\Cython\Distutils\old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
          "Cython.Distutils.old_build_ext does not properly handle dependencies "
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "C:\Users\swong32\AppData\Local\Temp\pip-build-hrf3b39s\pyhsmm\setup.py", line 11, in <module>
            from urllib import urlretrieve
        ImportError: cannot import name 'urlretrieve'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\swong32\AppData\Local\Temp\pip-build-hrf3b39s\pyhsmm\

I think it's because urllib.urlretrieve is now urllib.request.urlretrieve?

**Comment by mattjj** [comment]
Thanks for the find and diagnosis! I think I applied a fix using the future module, and I also added Python 3.4 to the .travis.yml file so that it gets tested.

Btw, that other warning that was printed seems to be [this issue with cython](https://github.com/cython/cython/issues/1509).

**Comment by stevenwong** [comment]
Argh, more issues

    Installed c:\program files\anaconda3\envs\py34\lib\site-packages\pyhsmm-0.1.6-py
    3.4-win-amd64.egg
    Processing dependencies for pyhsmm==0.1.6
    Searching for pybasicbayes>=0.1.3
    Reading https://pypi.python.org/simple/pybasicbayes/
    Downloading https://pypi.python.org/packages/dd/a9/2e5270c591dcafb85ef91696179a5
    f5620e683a7b6f35642ac6db1971209/pybasicbayes-0.2.1.tar.gz#md5=cee03ff871707a3adf
    302ec850942783
    Best match: pybasicbayes 0.2.1
    Processing pybasicbayes-0.2.1.tar.gz
    Writing C:\Users\swong32\AppData\Local\Temp\easy_install-ms7nxrn2\pybasicbayes-0
    .2.1\setup.cfg
    Running pybasicbayes-0.2.1\setup.py -q bdist_egg --dist-dir C:\Users\swong32\App
    Data\Local\Temp\easy_install-ms7nxrn2\pybasicbayes-0.2.1\egg-dist-tmp-05cij7bl
    C:\Program Files\Anaconda3\envs\py34\lib\site-packages\Cython\Distutils\old_buil
    d_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handl
    e dependencies and is deprecated.
      "Cython.Distutils.old_build_ext does not properly handle dependencies "
    Compiling pybasicbayes\util\cstats.pyx because it depends on C:\Program Files\An
    aconda3\envs\py34\lib\site-packages\Cython\Includes\numpy\__init__.pxd.
    [1/1] Cythonizing pybasicbayes\util\cstats.pyx

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        tmp[0,0] = 0
        tmp.flat[1:] = np.cumsum(np.ravel(customers)[:_customers.size-1],dtype=tmp.d
    type)
        cdef integral[:,::1] starts = tmp

        with nogil:
            for i in prange(_customers.shape[0]):
                 ^
    ------------------------------------------------------------

    pybasicbayes\util\cstats.pyx:70:14: Can only iterate over an iteration variable
    C:\Users\swong32\AppData\Local\Temp\easy_install-ms7nxrn2\pybasicbayes-0.2.1\set
    up.py:51: UserWarning: Failed to generate extension module code from Cython file
    s
      warn('Failed to generate extension module code from Cython files')
    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 156, in save_modules
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 197, in setup_context
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 246, in run_setup
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 276, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 245, in runner
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 47, in _execfile
      File "C:\Users\swong32\AppData\Local\Temp\easy_install-ms7nxrn2\pybasicbayes-0
    .2.1\setup.py", line 73, in <module>
        eigenpath = os.path.join('deps', 'Eigen')
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\core.py", line 148, i
    n setup
        dist.run_commands()
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\dist.py", line 955, i
    n run_commands
        self.run_command(cmd)
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\dist.py", line 974, i
    n run_command
        cmd_obj.run()
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\bdist_egg.py", line 152, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\cmd.py", line 313, in
     run_command
        self.distribution.run_command(command)
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\dist.py", line 974, i
    n run_command
        cmd_obj.run()
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\egg_info.py", line 195, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\egg_info.py", line 222, in find_sources
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\egg_info.py", line 306, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\egg_info.py", line 335, in add_defaults
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\sdist.py", line 171, in add_defaults
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\cmd.py", line 299, in
     get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\cmd.py", line 107, in
     ensure_finalized
        self.finalize_options()
      File "C:\Users\swong32\AppData\Local\Temp\easy_install-ms7nxrn2\pybasicbayes-0
    .2.1\setup.py", line 19, in finalize_options
        try:
    AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "setup.py", line 123, in <module>
        cmdclass={'build_ext': build_ext, 'sdist': sdist, 'clean': clean})
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\core.py", line 148, i
    n setup
        dist.run_commands()
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\dist.py", line 955, i
    n run_commands
        self.run_command(cmd)
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\dist.py", line 974, i
    n run_command
        cmd_obj.run()
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\install.py", line 67, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\install.py", line 117, in do_egg_install
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 409, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 645, in easy_install
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 696, in install_item
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 741, in process_distributio
    n
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\pkg_resources\__init__.py", line 851, in resolve
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\pkg_resources\__init__.py", line 1123, in best_match
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\pkg_resources\__init__.py", line 1135, in obtain
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 664, in easy_install
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 694, in install_item
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 875, in install_eggs
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 1114, in build_and_install
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\easy_install.py", line 1100, in run_setup
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 249, in run_setup
      File "C:\Program Files\Anaconda3\envs\py34\lib\contextlib.py", line 77, in __e
    xit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 197, in setup_context
      File "C:\Program Files\Anaconda3\envs\py34\lib\contextlib.py", line 77, in __e
    xit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 168, in save_modules
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 143, in resume
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 156, in save_modules
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 197, in setup_context
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 246, in run_setup
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 276, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 245, in runner
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\sandbox.py", line 47, in _execfile
      File "C:\Users\swong32\AppData\Local\Temp\easy_install-ms7nxrn2\pybasicbayes-0
    .2.1\setup.py", line 73, in <module>
        eigenpath = os.path.join('deps', 'Eigen')
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\core.py", line 148, i
    n setup
        dist.run_commands()
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\dist.py", line 955, i
    n run_commands
        self.run_command(cmd)
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\dist.py", line 974, i
    n run_command
        cmd_obj.run()
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\bdist_egg.py", line 152, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\cmd.py", line 313, in
     run_command
        self.distribution.run_command(command)
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\dist.py", line 974, i
    n run_command
        cmd_obj.run()
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\egg_info.py", line 195, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\egg_info.py", line 222, in find_sources
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\egg_info.py", line 306, in run
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\egg_info.py", line 335, in add_defaults
      File "C:\Program Files\Anaconda3\envs\py34\lib\site-packages\setuptools-27.2.0
    -py3.4.egg\setuptools\command\sdist.py", line 171, in add_defaults
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\cmd.py", line 299, in
     get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Program Files\Anaconda3\envs\py34\lib\distutils\cmd.py", line 107, in
     ensure_finalized
        self.finalize_options()
      File "C:\Users\swong32\AppData\Local\Temp\easy_install-ms7nxrn2\pybasicbayes-0
    .2.1\setup.py", line 19, in finalize_options
        try:
    AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
