### ISSUE TITLE
Readme example

### ISSUE THREAD

**Issue by tansey** [mattjj/pyhsmm#77]
I'm trying to just run the example in the readme and get the following error:

```
$ python pyhsmm/examples/hsmm.py
/usr/local/lib/python2.7/site-packages/pybasicbayes/distributions/multinomial.py:21: UserWarning: using slow sample_crp_tablecounts
  warn('using slow sample_crp_tablecounts')
/usr/local/lib/python2.7/site-packages/pybasicbayes/distributions/negativebinomial.py:25: UserWarning: using slow sample_crp_tablecounts
  warn('using slow sample_crp_tablecounts')
/usr/local/lib/python2.7/site-packages/pyhsmm/internals/transitions.py:17: UserWarning: using slow transition counting
  warn('using slow transition counting')

This demo shows the HDP-HSMM in action. Its iterations are slower than those for
the (Sticky-)HDP-HMM, but explicit duration modeling can be a big advantage for
conditioning the prior or for discovering structure in data.

Traceback (most recent call last):
  File "pyhsmm/examples/hsmm.py", line 52, in <module>
    posteriormodel.resample_model()
  File "/usr/local/lib/python2.7/site-packages/pyhsmm/models.py", line 442, in resample_model
    self.resample_states(num_procs=num_procs)
  File "/usr/local/lib/python2.7/site-packages/pyhsmm/models.py", line 467, in resample_states
    s.resample()
  File "/usr/local/lib/python2.7/site-packages/pyhsmm/internals/hsmm_states.py", line 325, in resample
    betal, betastarl = self.messages_backwards()
  File "/usr/local/lib/python2.7/site-packages/pyhsmm/internals/hsmm_states.py", line 503, in messages_backwards
    from pyhsmm.internals.hsmm_messages_interface import messages_backwards_log
ImportError: No module named hsmm_messages_interface
```

On OSX 10.12.4 with python 2.7.11. I tried building from source and using the pip install and both give the same error.

**Comment by tansey** [comment]
Got it! I recently upgraded to 10.12.x and it reset my gcc symlink back to clang. Also needed to `pip install -e .` from source.

**Comment by jason-su** [comment]
I have the same problem on Win10 with python 3.5
